### ISSUE TITLE
Default filters / queries

### ISSUE THREAD

**Issue by hangler** [bcgov/ExitSurveyAdmin#73]
We are going to want to have some of these set up for the user already. What should they be? Tagging in @karmour.

**Comment by karmour** [comment]
For now, I have three I can think of.

1.  Active users list (depending on our timeframe variable -- 3 or 6 months most likely)
2.  Active users from a specific time period (e.g., a calendar month) who have not yet submitted the survey, so we can send them paper reminders
3.  Full user list for the current fiscal reporting year (Apr - Mar)

**Comment by hangler** [comment]
@karmour As I actually implement these I think I need slightly more guidance 😅 What are the specific combination of filters we'd need in these? e.g. "Active users list" — is this based just on their status, or on their status + timeframe? We can discuss this morning.

**Comment by karmour** [comment]
Hi Frank, here are my thoughts:

1. Active users list -- if a user's Current Status is being governed by other criteria including only being set to "Active" if a) the user left within our timeframe limiter, b) has not yet completed the survey, and c) has not dropped off the CSV, then I think the filter could be pretty simple using only the "Active" criteria for Current Status.

2, If there's a way to auto-populate the filter with the previous month's start and end date (based on whatever today's month is), that would be great. But if not, then it seems like it would be pretty straight forward for us to do this ourselves.

3, Same as #2 - if there's a way for the filter to figure out that it should be auto-populating using the previous 1 year period (e.g., Apr 2019 - Mar 2020), then that would be great. If not, then we can run it ourselves pretty easily from the sound of it. 

@aclowery Amelia, can you let Frank know if there are any additional basic filtered searches beyond these that might be useful to be set up as one-click filters for you? Or are we OK with just the Active users (#1), and anything else we can manually run as needed? Sounds like manually setting a filter is pretty straight-forward.

**Comment by karmour** [comment]
Testing update: 
- Active Users pre-set filter is correctly using Statuses (note: the Statuses are not yet updated to the new list). 
- However, when clicking the link for "Active Employees" from the ESA landing page, the default filter has an EFFDT before 2020-06-03 instead of using Statuses.

**Comment by hangler** [comment]
This problem should be resolved on the new-and-updated landing page. Kindly re-test when you have a chance.

**Comment by hangler** [comment]
Oh, one question: @karmour, you mention both "current" and "previous" fiscal years in your comments above. I have implemented per your second comment, about the previous 1 year period (i.e. April 1, 2019 through March 31, 2020).

**Comment by karmour** [comment]
New landing page looks nice. :-)

1. Could we rename the "Exiting Employees" link in the top-right of the landing screen to be "Employee Database" instead, since this leads to the full unfiltered list?
2. Could we rename all remaining references of "Active employees" to be "Exiting Employees", including the preset filters?
3. Clicking the "Active Employees" preset filter multiple times causes the filter to be 'added' multiple times. See screen shot at bottom of message.
4. For Previous Month and Previous Year, could you tweak the date range very slightly to be one day earlier? So Apr 1 - Apr 30, for example, instead of Apr 1 - May 1. Same for Previous year -- should be Apr 1 to Mar 31.

Thanks!


![image](https://user-images.githubusercontent.com/5818030/85185258-1a7cd700-b248-11ea-9f9a-c1500566f17a.png)

**Comment by aclowery** [comment]
@hangler @karmour with reference to 2 above; the name still remains Active employees and will require the requested update. I am also noticing that this filter is still not working correctly... When I select the "Active Employees" filter, employees with "Employee not exiting" status still remain in the list.

**Comment by hangler** [comment]
These changes should all be made and @aclowery the bug you reported right above should also be fixed.

**Comment by karmour** [comment]
Previous Month and Previous year are now using the correct dates (#4 from my Jun 19 post). Amelia's filtering bug also appears fixed.

@hangler Could you look at #1-3 from Jun 19 and let me know if any of them are going to be problematic to change?

**Comment by hangler** [comment]
@karmour sorry, missed a couple of those. No, they should be easy to fix.

**Comment by karmour** [comment]
Found another bug with the default filters (sorry!). It appears that we can add both of the default date filters at once (previous month, previous fiscal year), but that only the one you clicked last will apply. Further, adding your own date filter acts the same -- if more than one date filter is active at once, only the latter-set filter applies. For example, if I click previous month first followed by previous fiscal year, the employee list only shows results for previous fiscal year. And if i re-click previous month at this point, it will now show results for the previous month but still show both filters engaged. See screen shots.

Previous month first, then Previous fiscal.
![image](https://user-images.githubusercontent.com/5818030/86067550-f8463e80-ba29-11ea-9af5-49fb4a7755b0.png)

Previous fiscal first, then Previous month.
![image](https://user-images.githubusercontent.com/5818030/86067587-10b65900-ba2a-11ea-99d8-e19d70785970.png)



Ultimately I think it's good that the app is only using one date-based filter at once. The issue is around how this is visualized in the app -- it's not necessarily clear that the app is only employing the last-set date filter when more than one appears active in blue. Could this be fixed so that it's more obvious that the second date filter replaces the first and is not co-active?

**Comment by hangler** [comment]
I have split the various items above into new tickets. Closing this one.
